# Generated by Django 4.1.6 on 2023-02-09 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(default=None, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, default=None, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=None, max_digits=10)),
                ('opening_hours', models.CharField(choices=[('8 am', '8:00'), ('9 am', '9:00'), ('10 am', '10:00'), ('11 am', '11:00'), ('12 am', '12:00'), ('1 pm', '13:00'), ('2 pm', '14:00'), ('3 pm', '15:00'), ('4 pm', '16:00'), ('5 pm', '17:00'), ('6 pm', '18:00'), ('7 pm', '19:00'), ('8 pm', '20:00'), ('9 pm', '21:00'), ('10 pm', '22:00'), ('11 pm', '23:00'), ('12 pm', '24:00')], default=None, max_length=100)),
                ('closing_hours', models.CharField(choices=[('8 am', '8:00'), ('9 am', '9:00'), ('10 am', '10:00'), ('11 am', '11:00'), ('12 am', '12:00'), ('1 pm', '13:00'), ('2 pm', '14:00'), ('3 pm', '15:00'), ('4 pm', '16:00'), ('5 pm', '17:00'), ('6 pm', '18:00'), ('7 pm', '19:00'), ('8 pm', '20:00'), ('9 pm', '21:00'), ('10 pm', '22:00'), ('11 pm', '23:00'), ('12 pm', '24:00')], default=None, max_length=100)),
                ('phone_number', models.CharField(default=None, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '998 [XX] [XXX XX XX]'. Up to 12 digits allowed.", regex='^998[0-9]{9}$')])),
                ('contact_link', models.URLField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
